### PR TITLE
Working example

### PR DESCRIPTION
**Pull request by TheAlexLichter**
Some comments:

* Async Data isn't needed here, but you *could* use it I think
* It's all about immutability here if I see it right. After navigating "back" to the page (where the content was missing), the `quotes` were already set in the data set.

### CODE REVIEW

**Comment by lunelson** [comment]
THANK YOU! Of course, that makes perfect sense! The `asyncData` and `data` functions are run every time I enter the route, but since `require`s are cached and I was not copying the array (which I supposed I could have done with just `times.slice()`) I was trying to transform something that had already been transformed... so it would seem the options here are either move the transformation out of the `asyncData` function, or (as in the case with my dynamicc routes), if I need the `params` object in order to know which file to `require`, I just have to copy the array if I'm going to do any transformation. Sound right?

**Comment by TheAlexLichter** [comment]
No problem!

Yup, that sounds good so far :relaxed: 
But be careful, as you edit objects inside arrays, so a shallow copy is likely not enough. You need a deep copy of that array!

The easiest way would be the JSON helpers:

`JSON.parse(JSON.stringify(array));`

**Comment by lunelson** [comment]
Ah, great tip. That's the first time that kind of thing has really bitten me, I didn't really think of that since I was using `Array.map` but I didn't foresee the dynamics of running the function every time the route was entered.

Thanks again, for taking the time.

**Comment by muhammadmusab** [comment]
I am having same issue , I am not using any array but I am putting the data from server in a variable for example 
in asyncData I am doing like this : 
return {
title:response.data.title
}

**Pull request closed without merging**
